[tools]
bun = "1.2.14"

[tasks.install]
depends = ["install:*"]

[tasks."install:deps"]
run = "bun install"

[tasks.codegen]
depends = ["codegen:*"]

[tasks."codegen:svelte"]
run = "bun run svelte-kit sync"
depends = ["install"]

[tasks.test]
depends = ["test:*"]

[tasks."test:unit"]
run = "bun run vitest run"
depends = ["install", "codegen"]

[tasks.lint]
run = "./scripts/workspaced codebase lint"
depends = ["install", "codegen"]

[tasks.fmt]
run = "./scripts/workspaced codebase format"
depends = ["install"]

[tasks.ci]
depends = ["lint", "test"]

[tasks.build]
run = "bun run build"
depends = ["install", "codegen"]
